spring:
  application:
    name: deslrey-java
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 200381
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6370


mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  servlet:
    context-path: /deslrey/api
  port: 8080


custom:
  static-source-path: D:\repository\images
  url: http://localhost:8080/deslrey/api/staticSource/

carousel:
  sex-api: http://localhost:8080/deslrey/api/staticSource/bg/sex/
  scenery-api: http://localhost:8080/deslrey/api/staticSource/bg/scenery/
